export const BOARD_LIST_REQUEST = "BOARD_LIST_REQUEST"
export const BOARD_LIST_SUCCESS = "BOARD_LIST_SUCCESS"
export const BOARD_LIST_FAIL = "BOARD_LIST_FAIL"

export const BOARD_ADD_TOTAL_REQUEST = "BOARD_ADD_TOTAL_REQUEST"
export const BOARD_ADD_TOTAL_SUCCESS = "BOARD_ADD_TOTAL_SUCCESS"
export const BOARD_ADD_TOTAL_FAIL = "BOARD_ADD_TOTAL_FAIL"