export const TOOL_LIST_REQUEST = "TOOL_LIST_REQUEST"
export const TOOL_LIST_SUCCESS = "TOOL_LIST_SUCCESS"
export const TOOL_LIST_FAIL = "TOOL_LIST_FAIL"

export const TOOL_ADD_TOTAL_REQUEST = "TOOL_ADD_TOTAL_REQUEST"
export const TOOL_ADD_TOTAL_SUCCESS = "TOOL_ADD_TOTAL_SUCCESS"
export const TOOL_ADD_TOTAL_FAIL = "TOOL_ADD_TOTAL_FAIL"